export const SET_TIMETABLE = "SET_TIMETABLE" ;

export const SET_LIST_SUBJECTS = "SET_LIST_SUBJECTS";

export const UNSET_LIST_SUBJECTS = "UNSET_LIST_SUBJECTS";

export const SET_CHOSEN_SUBJECT = "SET_CHOSEN_SUBJECT";

export const UNSET_CHOSEN_SUBJECT = "UNSET_CHOSEN_SUBJECT";

export const SET_VALID_TIMETABLE = "SET_VALID_TIMETABLE";

export const SET_IS_VALID_TIMETABLE = "SET_IS_VALID_TIMETABLE";